services:
  dream-match:
    build: ./
    ports:
      - '3000:3000'
    env_file:
      - ./.env.local
    volumes:
      - ./:/dream-match
      - /dream-match/node_modules
    command: npm run dev
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/mongodb

volumes:
  db_data:
